import { 
  Home, Zap, ShoppingCart, MessageSquare, Sparkles, Flame, Calendar, Layers, Star, Gift, Feather, Heart, Sun, Palette, Shield, Smile, Image as ImageIcon, Wallet, Grid
} from 'lucide-react';
import { LanguageCode, MenuItem, TranslationStructure, MicroItem } from './types';

export const USER_ID = "User_092024";
export const TAROT_CARDS = ["The Fool", "The Magician", "The High Priestess", "The Empress", "The Emperor", "The Hierophant", "The Lovers", "The Chariot", "Strength", "The Hermit", "Wheel of Fortune", "Justice", "The Hanged Man", "Death", "Temperance", "The Devil", "The Tower", "The Star", "The Moon", "The Sun", "Judgement", "The World"];

export const GOD_BIRTHDAYS = [
    { month: 1, days: [{ day: 1, name: "元始天尊萬壽" }, { day: 5, name: "迎財神" }, { day: 9, name: "玉皇上帝萬壽" }] },
    { month: 2, days: [{ day: 2, name: "福德正神千秋" }, { day: 19, name: "觀世音菩薩佛辰" }] },
    { month: 3, days: [{ day: 15, name: "保生大帝千秋" }, { day: 23, name: "天上聖母聖誕" }] },
    { month: 4, days: [{ day: 8, name: "釋迦佛祖萬壽" }, { day: 26, name: "神農大帝聖誕" }] },
    { month: 5, days: [{ day: 13, name: "城隍爺聖誕" }] },
    { month: 6, days: [{ day: 6, name: "虎爺聖誕" }, { day: 19, name: "觀世音菩薩得道" }] },
    { month: 7, days: [{ day: 7, name: "七星娘娘千秋" }, { day: 15, name: "中元地官聖誕" }, { day: 30, name: "地藏王菩薩佛辰" }] },
    { month: 8, days: [{ day: 15, name: "月下老人聖誕" }, { day: 27, name: "孔子聖誕" }] },
    { month: 9, days: [{ day: 9, name: "中壇元帥聖誕" }, { day: 19, name: "觀世音菩薩出家" }] },
    { month: 10, days: [{ day: 5, name: "達摩祖師佛辰" }, { day: 15, name: "下元水官大帝聖誕" }] },
    { month: 11, days: [{ day: 17, name: "阿彌陀佛佛辰" }] },
    { month: 12, days: [{ day: 16, name: "尾牙福德正神" }, { day: 24, name: "送神日" }] }
];

export const MENU_ITEMS: MenuItem[] = [
  { id: 'dashboard', translationKey: 'dashboard', icon: Home },
  { id: 'dailyDraw', translationKey: 'dailyDraw', icon: Zap },
  { id: 'tarot', translationKey: 'tarot', icon: Layers }, 
  { id: 'nameBlessing', translationKey: 'nameBlessing', icon: Sparkles },
  { id: 'rituals', translationKey: 'rituals', icon: Flame },
  { id: 'lunarCalendar', translationKey: 'lunarCalendar', icon: Calendar }, 
  { id: 'yearlyFortune', translationKey: 'yearlyFortune', icon: Calendar },
  { id: 'aiStudio', translationKey: 'aiStudio', icon: ImageIcon },
  { id: 'sageChat', translationKey: 'sageChat', icon: MessageSquare, badge: 1 },
  { id: 'shop', translationKey: 'shop', icon: ShoppingCart },
  { id: 'wallet', translationKey: 'wallet', icon: Wallet },
  { id: 'gallery', translationKey: 'gallery', icon: Grid },
];

export const MICRO_SHOP_ITEMS: MicroItem[] = [
  { id: 'lucky_sign', nameKey: '今日好運籤', price: 10, icon: Sparkles, type: 'text', color: 'bg-pink-50 text-pink-700 border-pink-300' },
  { id: 'wealth_mantra', nameKey: '今日財運吉語卡', price: 20, icon: Star, type: 'card', color: 'bg-gray-50 text-gray-700 border-gray-300' },
  { id: 'merit_point', nameKey: '電子功德點', price: 20, icon: Heart, type: 'card', color: 'bg-rose-50 text-rose-700 border-rose-300' },
  { id: 'mini_lamp', nameKey: '小小祈福燈', price: 30, icon: Flame, type: 'card', color: 'bg-orange-50 text-orange-700 border-orange-300' },
  { id: 'money_magnet', nameKey: '金錢磁場啟動詞', price: 10, icon: Zap, type: 'text', color: 'bg-yellow-50 text-yellow-800 border-yellow-400' },
  { id: 'wish_amulet', nameKey: '心願小護符', price: 30, icon: Shield, type: 'card', color: 'bg-purple-50 text-purple-700 border-purple-300' },
  { id: 'daily_bless', nameKey: '每日一句祝福', price: 20, icon: Smile, type: 'text', color: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-300' },
  { id: 'zodiac_guide', nameKey: '生肖今日指引', price: 10, icon: Calendar, type: 'input_zodiac', color: 'bg-blue-50 text-blue-700 border-blue-300' },
  { id: 'wish_note', nameKey: '祈願小紙條', price: 20, icon: Feather, type: 'input_wish', color: 'bg-indigo-50 text-indigo-700 border-indigo-300' },
  { id: 'spiritual_calm', nameKey: '靈性安定語', price: 10, icon: Layers, type: 'card', color: 'bg-slate-50 text-slate-700 border-slate-300' },
  { id: 'wish_booster', nameKey: '心願加速包', price: 20, icon: Zap, type: 'text', color: 'bg-red-50 text-red-800 border-red-400' },
  { id: 'wealth_god_card', nameKey: '財神助力卡', price: 30, icon: Star, type: 'card', color: 'bg-yellow-100 text-yellow-800 border-yellow-500' },
  { id: 'stress_amulet', nameKey: '解憂平安符', price: 20, icon: Shield, type: 'card', color: 'bg-green-50 text-green-800 border-green-500' },
  { id: 'family_safe', nameKey: '家庭平安祈福卡', price: 30, icon: Home, type: 'card', color: 'bg-orange-100 text-orange-800 border-orange-500' },
  { id: 'luck_boost_3d', nameKey: '運勢補運包(3天)', price: 30, icon: Gift, type: 'text', color: 'bg-purple-100 text-purple-800 border-purple-500' },
  { id: 'quick_qa', nameKey: '快速問事', price: 30, icon: MessageSquare, type: 'input_question', color: 'bg-blue-100 text-blue-800 border-blue-500' },
  { id: 'lucky_color', nameKey: '今日開運色建議', price: 10, icon: Palette, type: 'text', color: 'bg-pink-100 text-pink-800 border-pink-500' },
  { id: 'wealth_wallpaper', nameKey: '財運桌布', price: 10, icon: Sparkles, type: 'card', color: 'bg-gray-100 text-gray-900 border-gray-600' },
  { id: 'animated_guardian', nameKey: '平安守護AI動態', price: 30, icon: Sun, type: 'card', color: 'bg-cyan-50 text-cyan-700 border-cyan-300' },
  { id: 'quotes_10', nameKey: '靈性暖心語錄', price: 20, icon: Heart, type: 'text', color: 'bg-rose-50 text-rose-700 border-rose-300' },
];

export const t = (lang: LanguageCode, key: keyof TranslationStructure): string => {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS['en']?.[key] || String(key);
};

// --- STRIPE PAYMENT LINKS (COMPLETE) ---
export const STRIPE_PRICES = {
  // Unlocks
  unlock_daily_draw: "https://buy.stripe.com/14AaEZ2ol5pS2704VF9ws0l",
  unlock_tarot: "https://buy.stripe.com/3cI6oJ8MJ4lObHA0Fp9ws0k",
  unlock_yearly_fortune: "https://buy.stripe.com/aFa14pd2Z8C47rk0Fp9ws0j",
  
  // Rituals
  rituals_lamp: "https://buy.stripe.com/bJe7sNfb77y012W2Nx9ws0i",
  rituals_wealth: "https://buy.stripe.com/8x2cN70gd19C4f8afZ9ws0h",
  rituals_karmic: "https://buy.stripe.com/dRm6oJe737y09zs0Fp9ws0g",
  
  // Membership
  shop_plan299: "https://buy.stripe.com/8x2aEZe733hKeTM73N9ws0f",
  
  // Shop Items
  shop_item1: "https://buy.stripe.com/8x2cN71kh6tWcLE5ZJ9ws0e",
  shop_item2: "https://buy.stripe.com/5kQcN7bYVbOgdPIfAj9ws0d",
  shop_item3: "https://buy.stripe.com/6oUeVffb7f0s2709bV9ws0c",
  shop_video: "https://buy.stripe.com/00w7sN3spf0s270bk39ws0b",
  shop_wallpaper: "https://buy.stripe.com/fZu6oJ4wtcSk4f8bk39ws0a",
  
  // Coin Packs
  coin_pack_1: "https://buy.stripe.com/7sYfZjd2Z4lO3b487R9ws07",
  coin_pack_2: "https://buy.stripe.com/eVq28tgfb3hKcLE3RB9ws08",
  coin_pack_3: "https://buy.stripe.com/7sY8wRe732dG8vobk39ws09",
};

export const TRANSLATIONS: Record<LanguageCode, TranslationStructure> = {
  zh_TW: {
    appName: "點讚添好運添福報助手",
    version: "版本 v3.9 (Direct Payment)",
    traditionalChinese: "繁體中文",
    simplifiedChinese: "简体中文",
    english: "English",
    userID: "用戶 ID",
    dashboard: "福報概覽",
    fortuneIndex: "福報指數",
    familyHarmony: "家庭和睦",
    compatibility: "正緣匹配",
    dailyDraw: "每日一籤", 
    tarot: "塔羅占卜", 
    nameBlessing: "姓名祈福 (12 福幣)",
    rituals: "祈福法會",
    yearlyFortune: "專屬流年",
    merits: "功德紀錄",
    kindnessShare: "善行分享",
    sageChat: "智者連線",
    shop: "福祿堂",
    lunarCalendar: "神明聖誕",
    aiStudio: "靈境工坊",
    wallet: "福報存摺",
    gallery: "內容庫",
    welcome: "媽祖保佑，好運一路發！",
    totalUsage: "總使用時長 (天)",
    fortuneIndexTitle: "今日福報指數",
    target: "（目標 90 分以上）",
    dailyTarget: "日功德目標 (個)",
    weeklyFocus: "本週修行重點",
    fortuneTrend: "福報走勢圖 (模擬)",
    quickGuide: "快速指南",
    guideText: "點擊左側菜單，開始您的修行旅程。",
    drawFortune: "點擊抽取今日一籤", 
    drawing: "正在抽籤...",
    blessing: "萬事如意",
    topBlessing: "上上籤",
    topSign: "上籤",
    middleSign: "中籤",
    lowSign: "下籤",
    heavenMatch: "天作之合，恭喜您！",
    goodMatch: "緣分深厚，還需磨合。",
    fateAccept: "緣起緣滅，隨緣就好。",
    comingSoon: "即將推出...",
    fortuneDesc1: "機緣已到，心想事成，宜積極進取。",
    fortuneDesc2: "努力有成，貴人相助，名利雙收。",
    fortuneDesc3: "凡事勿急，按部就班，可得圓滿。",
    fortuneDesc4: "時機未到，退守保本，靜觀其變。",
    deepAnalysisTitle: "完整指示 & 運勢詳解",
    unlockAnalysis: "每日一籤深度解析 (NT$99)",
    unlockPrompt: "想解鎖完整指示？",
    paymentProcessing: "正在前往付款頁面...",
    paymentSuccess: "付款成功！",
    generatingAi: "大師正在感應天機...",

    tarot_title: "塔羅牌靈感占卜",
    tarot_desc: "請在心中默念您的問題，然後抽取三張牌，揭示過去、現在與未來。",
    tarot_start_btn: "開始洗牌",
    tarot_picking: "請憑直覺選取 3 張牌...",
    tarot_reveal_title: "牌面揭曉",
    tarot_past: "過去 (根源)",
    tarot_present: "現在 (處境)",
    tarot_future: "未來 (指引)",
    tarot_unlock_btn: "塔羅牌陣詳解 (NT$99)",
    tarot_locked_msg: "想知道牌面背後的完整天機與建議？",

    bless_inputName: "請輸入祈福姓名",
    bless_selectType: "選擇祈福類別",
    bless_type_health: "健康平安",
    bless_type_wealth: "財源廣進",
    bless_type_love: "良緣美滿",
    bless_type_career: "事業騰飛",
    bless_generate: "生成祈福卡 (12 福幣)",
    bless_cardTitle: "祈福靈籤",
    bless_voice_upgrade: "加購大師親口誦經祈福 (12 福幣)",
    bless_play_voice: "播放大師祈福語音",

    rituals_title: "線上祈福法會",
    rituals_lamp_name: "光明平安燈 (NT$199)",
    rituals_lamp_desc: "光明照耀，前程似錦，保佑阖家平安。",
    rituals_wealth_name: "補財庫法會 (NT$888)",
    rituals_wealth_desc: "填補財庫漏洞，聚财納福，財運亨通。",
    rituals_karmic_name: "消災解厄法會 (NT$500)",
    rituals_karmic_desc: "化解冤親債主，消除業障，身心清淨。",
    rituals_perform_btn: "立即報名法會",
    rituals_prayer_title: "法會疏文 (大師親批)",
    rituals_audio_btn: "聆聽大師誦經加持",
    rituals_seasonal_title: "節日祈福 (平安燈 NT$199)",

    peaceLamp: "平安燈",
    lamp_title: "點灯祈福",
    lamp_desc: "點燃心灯，照亮前程，保佑阖家平安。",
    lamp_lit_msg: "光明已点亮，福澤將至。",
    lamp_light_btn: "立即點燈 (NT$199)",

    yearly_title: "個人專屬流年運勢",
    yearly_desc: "輸入生辰八字，大師為您推算未來一年流年運勢，趨吉避凶。",
    yearly_input_name: "真實姓名",
    yearly_input_birth: "出生日期 (國曆/農曆)",
    yearly_unlock_btn: "個人流年運勢詳批 (NT$299)",
    yearly_report_title: "流年運勢詳解",

    analysis_title: "福報指數分析",
    analysis_inputLesson: "時辰功課",
    analysis_inputStability: "心境平穩度",
    analysis_calculate: "立即計算",
    analysis_trend: "歷史福報趨勢",

    harmony_title: "家庭和睦參數設定",
    harmony_nicknameSubtitle: "設定清晰，避免誤會。",
    harmony_save: "保存和睦參數",
    harmony_timeLabel: "設定時間",
    harmony_daysLabel: "共修日數",
    harmony_setReminder: "設定提醒",

    comp_title: "正緣匹配速查",
    comp_yourLabel: "您的尊稱",
    comp_partnerLabel: "對方尊稱",
    comp_calc: "測算匹配度",
    comp_result: "匹配結果",

    task_title: "功德任務紀錄",
    task_today: "今日待辦功課",
    task_save: "保存今日進度",
    task_1: "助人為樂",
    task_2: "早起行善",
    task_3: "靜坐十分鐘",

    share_title: "善行分享",
    share_gen_title: "分享故事生成器",
    share_placeholder: "輸入您的善行事蹟簡述...",
    share_btn: "生成分享文案",

    chat_title: "大師問事廳",
    chat_select_deity: "請選擇問事對象",
    chat_placeholder: "請輸入您的問題 (請神需心誠)...",
    chat_send: "發送",
    chat_history_clear: "結束對話",
    deity_landgod: "土地公",
    deity_landgod_desc: "守護鄉里，指點迷津 (免費)",
    deity_wealth: "五路財神",
    deity_wealth_desc: "求財運、事業、投資 (10 福幣/次)",
    deity_matchmaker: "月下老人",
    deity_matchmaker_desc: "求姻緣、紅線、復合 (10 福幣/次)",
    deity_mazu: "天上聖母",
    deity_mazu_desc: "求平安、健康、心事 (20 福幣/次)",
    deity_guanyu: "關聖帝君",
    deity_guanyu_desc: "求功名、決策、除小人 (20 福幣/次)",
    chat_offering_title: "請神供養",
    chat_offering_basic: "清香一柱 (10 福幣)",
    chat_offering_premium: "金牌一面 (50 福幣)",
    chat_unlock_btn: "確認供養並開始問事",

    shop_title: "福祿堂",
    shop_add: "加入購物車",
    shop_checkout: "結帳區",
    shop_total: "購物車總計",
    shop_pay: "立即結帳",
    shop_popular: "熱銷推薦",
    shop_plan99_name: "單次深度解析 (NT$99)",
    shop_plan99_desc: "解鎖單次運勢詳解，包含事業、感情、健康全方位分析。",
    shop_plan299_name: "尊榮會員訂閱 (NT$299/月)",
    shop_plan299_desc: "每日祈福、每週幸運日提醒、每月專屬開運卡。",
    shop_item1_name: "開運硃砂手串",
    shop_item1_desc: "大師加持，避邪招財 (NT$499)。",
    shop_item2_name: "旺財聚寶盆",
    shop_item2_desc: "財源滾滾來，事業興旺 (NT$399)。",
    shop_item3_name: "平安符香火袋",
    shop_item3_desc: "隨身攜帶，出入平安 (NT$299)。",
    shop_video_name: "專屬祈福影片 (NT$199)",
    shop_video_desc: "大師親自為您錄製祈福影片，誠意滿滿。",
    shop_wallpaper_name: "開運手機桌布 (NT$50)",
    shop_wallpaper_desc: "每日一換，好運常伴。",
    shop_micro_title: "每日小確幸 (10-60 福幣)",
    shop_micro_desc: "小額祈福，隨時隨地開啟好運磁場。",
    shop_delivery_title: "您的數位開運商品已送達",
    shop_delivery_save: "長按保存圖片/文字",
    shop_input_wish: "請輸入您的願望",
    shop_input_question: "請輸入您的問題",
    shop_input_zodiac: "請選擇您的生肖",

    festival_qingming: "清明祭祖",
    festival_ghost: "中元普渡",
    festival_ghost_14: "農曆七月十四",
    festival_cny: "新春祈福",
    festival_lantern: "元宵點燈",
    festival_mazu: "媽祖聖誕",
    festival_qingming_desc: "慎終追遠，祭拜祖先。",
    festival_ghost_desc: "普渡眾生，化解冤親。",
    festival_ghost_14_desc: "祭拜好兄弟，祈求平安。",
    festival_cny_desc: "迎春接福，開運招财。",
    festival_lantern_desc: "點亮心灯，增長智慧。",
    festival_mazu_desc: "天上聖母，護佑平安。",

    calendar_title: "神明聖誕千秋",
    calendar_btn: "為神明點燈 (NT$199)",

    ai_studio_title: "AI 靈境工坊",
    ai_studio_desc: "運用天機 AI 生成專屬祈福聖像。",
    ai_credits_balance: "福幣餘額",
    ai_buy_credits: "儲值福幣",
    ai_input_placeholder: "輸入祈福對象 (例如: 媽祖, 關公, 財神)",
    ai_generate_image: "生成祈福聖像",
    ai_generate_video: "生成祈福影片",
    ai_cost_image: "10 福幣",
    ai_cost_video: "50 福幣",
    ai_generating: "大師正在施法生成中...",
    ai_pack_1: "福幣 - 初心體驗包 (NT$99)",
    ai_pack_1_desc: "可生成 1 部影片或 10 張聖像。",
    ai_pack_2: "福幣 - 誠心加持包 (NT$299)",
    ai_pack_2_desc: "省33% - 可生成 7 部影片或 35 張聖像。",
    ai_pack_3: "福幣 - 功德無量包 (NT$999)",
    ai_pack_3_desc: "最超值 - 可生成 24 部影片或 120 張聖像。",
    ai_badge_hot: "熱銷推薦",
    ai_badge_best: "最超值",
    
    ai_result_title: "✨ 天賜靈畫 ✨",
    ai_error_title: "天機連線中斷",
    ai_error_desc: "感應訊號微弱（可能因神聖法相過於莊嚴，暫時無法顯化）。\n請嘗試修改描述或稍後再試。",
    ai_refund_msg: "✅ {cost} 福幣已自動退還",
    ai_bonus_msg: "🎁 額外贈送 +10 福幣結緣金",
    ai_close_btn: "關閉並重試",

    login_title: "加入點讚添好運",
    login_subtitle: "登入即可累積福報、領取每日福幣",
    login_google: "使用 Google 登入 (模擬)",
    login_facebook: "使用 Facebook 登入 (模擬)",
    checkin_title: "每日簽到",
    checkin_btn: "立即簽到領福幣",
    checkin_success: "簽到成功！",
    checkin_streak: "連續簽到",
    checkin_reward: "+10 福幣",

    wallet_title: "我的福報存摺",
    gallery_title: "內容庫 (已保存)",
    support_btn: "聯絡助教 / 客服",
    wallet_history: "交易紀錄",
    wallet_topup: "儲值",
    wallet_spend: "消費",
    gallery_empty: "尚無保存內容，快去靈境工坊生成吧！",
  },
  zh_CN: {
    appName: "点赞添好运添福报助手",
    version: "版本 v3.9 (Direct Payment)",
    traditionalChinese: "繁体中文",
    simplifiedChinese: "简体中文",
    english: "English",
    userID: "用户 ID",
    dashboard: "福报概览",
    fortuneIndex: "福报指数",
    familyHarmony: "家庭和睦",
    compatibility: "正缘匹配",
    dailyDraw: "每日一签",
    tarot: "塔罗占卜",
    nameBlessing: "姓名祈福 (12 福币)",
    rituals: "祈福法会",
    yearlyFortune: "专属流年",
    merits: "功德记录",
    kindnessShare: "善行分享",
    sageChat: "智者连线",
    shop: "福禄堂",
    lunarCalendar: "神明圣诞",
    aiStudio: "灵境工坊",
    wallet: "福报存折",
    gallery: "内容库",
    welcome: "妈祖保佑，好运一路发！",
    totalUsage: "总使用时长 (天)",
    fortuneIndexTitle: "今日福报指数",
    target: "（目标 90 分以上）",
    dailyTarget: "日功德目标 (个)",
    weeklyFocus: "本周修行重点",
    fortuneTrend: "福报走势图 (模拟)",
    quickGuide: "快速指南",
    guideText: "点击左侧菜单，开始您的修行旅程。",
    drawFortune: "点击抽取今日一签",
    drawing: "正在抽签...",
    blessing: "万事如意",
    topBlessing: "上上签",
    topSign: "上签",
    middleSign: "中签",
    lowSign: "下签",
    heavenMatch: "天作之合，恭喜您！",
    goodMatch: "缘分深厚，还需磨合。",
    fateAccept: "缘起缘灭，随缘就好。",
    comingSoon: "即将推出...",
    fortuneDesc1: "机缘已到，心想事成，宜积极进取。",
    fortuneDesc2: "努力有成，贵人相助，名利双收。",
    fortuneDesc3: "凡事勿急，按部就班，可得圆满。",
    fortuneDesc4: "时机未到，退守保本，静观其变。",
    deepAnalysisTitle: "完整指示 & 运势详解",
    unlockAnalysis: "每日一签深度解析 (NT$99)",
    unlockPrompt: "想解锁完整指示？",
    paymentProcessing: "正在前往付款页面...",
    paymentSuccess: "付款成功！",
    generatingAi: "大师正在感应天机...",

    tarot_title: "塔罗牌灵感占卜",
    tarot_desc: "请在心中默念您的问题，然后抽取三张牌，揭示过去、现在与未来。",
    tarot_start_btn: "开始洗牌",
    tarot_picking: "请凭直觉选取 3 张牌...",
    tarot_reveal_title: "牌面揭晓",
    tarot_past: "过去 (根源)",
    tarot_present: "现在 (处境)",
    tarot_future: "未来 (指引)",
    tarot_unlock_btn: "塔罗牌阵详解 (NT$99)",
    tarot_locked_msg: "想知道牌面背后的完整天机与建议？",

    bless_inputName: "请输入祈福姓名",
    bless_selectType: "选择祈福类别",
    bless_type_health: "健康平安",
    bless_type_wealth: "财源广进",
    bless_type_love: "良缘美满",
    bless_type_career: "事业腾飞",
    bless_generate: "生成祈福卡 (12 福币)",
    bless_cardTitle: "祈福灵签",
    bless_voice_upgrade: "加购大师亲口诵经祈福 (12 福币)",
    bless_play_voice: "播放大师祈福语音",

    rituals_title: "线上祈福法会",
    rituals_lamp_name: "光明平安灯 (NT$199)",
    rituals_lamp_desc: "光明照耀，前程似锦，保佑阖家平安。",
    rituals_wealth_name: "年底补财库 (NT$888)",
    rituals_wealth_desc: "填补财库漏洞，聚财纳福，财运亨通。",
    rituals_karmic_name: "消灾解厄仪式 (NT$500)",
    rituals_karmic_desc: "化解冤亲债主，消除业障，身心清净。",
    rituals_perform_btn: "立即报名法会",
    rituals_prayer_title: "法会疏文 (大师亲批)",
    rituals_audio_btn: "聆听大师诵经加持",
    rituals_seasonal_title: "节日祈福 (平安灯 NT$199)",

    peaceLamp: "平安灯",
    lamp_title: "点灯祈福",
    lamp_desc: "点燃心灯，照亮前程，保佑阖家平安。",
    lamp_lit_msg: "光明已点亮，福泽将至。",
    lamp_light_btn: "立即点灯 (NT$199)",

    yearly_title: "个人专属流年运势",
    yearly_desc: "输入生辰八字，大师为您推算未来一年流年运势，趋吉避凶。",
    yearly_input_name: "真实姓名",
    yearly_input_birth: "出生日期 (国历/农历)",
    yearly_unlock_btn: "解锁流年详批 (NT$299)",
    yearly_report_title: "流年运势详解",

    analysis_title: "福报指数分析",
    analysis_inputLesson: "时辰功课",
    analysis_inputStability: "心境平稳度",
    analysis_calculate: "立即计算",
    analysis_trend: "历史福报趋势",

    harmony_title: "家庭和睦参数设定",
    harmony_nicknameSubtitle: "设定清晰，避免误会。",
    harmony_save: "保存和睦参数",
    harmony_timeLabel: "设定时间",
    harmony_daysLabel: "共修日数",
    harmony_setReminder: "设定提醒",

    comp_title: "正缘匹配速查",
    comp_yourLabel: "您的尊称",
    comp_partnerLabel: "对方尊称",
    comp_calc: "测算匹配度",
    comp_result: "匹配结果",

    task_title: "功德任务纪录",
    task_today: "今日待办功课",
    task_save: "保存今日进度",
    task_1: "助人为乐",
    task_2: "早起行善",
    task_3: "静坐十分钟",

    share_title: "善行分享",
    share_gen_title: "分享故事生成器",
    share_placeholder: "输入您的善行事迹简述...",
    share_btn: "生成分享文案",

    chat_title: "大师问事厅",
    chat_select_deity: "请选择问事对象",
    chat_placeholder: "请输入您的问题 (请神需心诚)...",
    chat_send: "发送",
    chat_history_clear: "结束对话",
    deity_landgod: "土地公",
    deity_landgod_desc: "守护乡里，指点迷津 (免费)",
    deity_wealth: "五路财神",
    deity_wealth_desc: "求财运、事业、投资 (10 福币/次)",
    deity_matchmaker: "月下老人",
    deity_matchmaker_desc: "求姻缘、红线、复合 (10 福币/次)",
    deity_mazu: "天上圣母",
    deity_mazu_desc: "求平安、健康、心事 (20 福币/次)",
    deity_guanyu: "关圣帝君",
    deity_guanyu_desc: "求功名、决策、除小人 (20 福币/次)",
    chat_offering_title: "请神供养",
    chat_offering_basic: "清香一柱 (10 福币)",
    chat_offering_premium: "金牌一面 (50 福币)",
    chat_unlock_btn: "确认供养并开始问事",

    shop_title: "幸运小铺",
    shop_add: "加入购物车",
    shop_checkout: "结帐区",
    shop_total: "购物车总计",
    shop_pay: "立即结帐",
    shop_popular: "热销推荐",
    shop_plan99_name: "单次深度解析 (NT$99)",
    shop_plan99_desc: "解锁单次运势详解，包含事业、感情、健康全方位分析。",
    shop_plan299_name: "尊荣会员订阅 (NT$299/月)",
    shop_plan299_desc: "每日祈福、每周幸运日提醒、每月专属开运卡。",
    shop_item1_name: "开运朱砂手串",
    shop_item1_desc: "大师加持，避邪招财 (NT$499)。",
    shop_item2_name: "旺财聚宝盆",
    shop_item2_desc: "财源滚滚来，事业兴旺 (NT$399)。",
    shop_item3_name: "平安符香火袋",
    shop_item3_desc: "随身携带，出入平安 (NT$299)。",
    shop_video_name: "专属祈福影片 (NT$199)",
    shop_video_desc: "大师亲自为您录制祈福影片，诚意满满。",
    shop_wallpaper_name: "手机开运壁纸 (NT$50)",
    shop_wallpaper_desc: "每日一换，好运常伴。",
    shop_micro_title: "每日小确幸 (10-60 福币)",
    shop_micro_desc: "小额祈福，随时随地开启好运磁场。",
    shop_delivery_title: "您的数位开运商品已送达",
    shop_delivery_save: "长按保存图片/文字",
    shop_input_wish: "请输入您的愿望",
    shop_input_question: "请输入您的问题",
    shop_input_zodiac: "请选择您的生肖",

    festival_qingming: "清明祭祖",
    festival_ghost: "中元普渡",
    festival_ghost_14: "农历七月十四",
    festival_cny: "新春祈福",
    festival_lantern: "元宵点灯",
    festival_mazu: "妈祖圣诞",
    festival_qingming_desc: "慎终追远，祭拜祖先。",
    festival_ghost_desc: "普渡众生，化解冤亲。",
    festival_ghost_14_desc: "祭拜好兄弟，祈求平安。",
    festival_cny_desc: "迎春接福，开运招财。",
    festival_lantern_desc: "点亮心灯，增长智慧。",
    festival_mazu_desc: "天上圣母，护佑平安。",

    calendar_title: "神明圣诞千秋",
    calendar_btn: "为神明点灯 (NT$199)",

    ai_studio_title: "AI 灵境工坊",
    ai_studio_desc: "运用天机 AI 生成专属祈福圣像 (Chibi Q版)。",
    ai_credits_balance: "福币余额",
    ai_buy_credits: "储值福币",
    ai_input_placeholder: "输入祈福对象 (例如: 妈祖, 关公, 财神)",
    ai_generate_image: "生成祈福圣像",
    ai_generate_video: "生成祈福影片",
    ai_cost_image: "10 福币",
    ai_cost_video: "50 福币",
    ai_generating: "大师正在施法生成中...",
    ai_pack_1: "福币 - 初心体验包 (NT$99)",
    ai_pack_1_desc: "初心体验包 - 可生成 1 部影片或 10 張聖像。",
    ai_pack_2: "福币 - 诚心加持包 (NT$299)",
    ai_pack_2_desc: "诚心加持包 (省33%) - 可生成 7 部影片或 35 张圣像。",
    ai_pack_3: "福币 - 功德无量包 (NT$999)",
    ai_pack_3_desc: "功德无量包 (最超值) - 可生成 24 部影片或 120 张圣像。",
    ai_badge_hot: "热销推荐",
    ai_badge_best: "最超值",
    
    ai_result_title: "✨ 天赐灵画 ✨",
    ai_error_title: "天机连线中断",
    ai_error_desc: "感应讯号微弱（可能因神圣法相过于庄严，暂时无法显化）。\n请尝试修改描述或稍后再试。",
    ai_refund_msg: "✅ {cost} 福币已自动退还",
    ai_bonus_msg: "🎁 额外赠送 +10 福币结缘金",
    ai_close_btn: "关闭并重试",

    login_title: "加入点赞添好运",
    login_subtitle: "登入即可累积福报、领取每日福币",
    login_google: "使用 Google 登入 (模拟)",
    login_facebook: "使用 Facebook 登入 (模拟)",
    checkin_title: "每日签到",
    checkin_btn: "立即签到领福币",
    checkin_success: "签到成功！",
    checkin_streak: "连续签到",
    checkin_reward: "+10 福币",

    wallet_title: "我的福报存折",
    gallery_title: "内容库 (已保存)",
    support_btn: "联络助教 / 客服",
    wallet_history: "交易纪录",
    wallet_topup: "储值",
    wallet_spend: "消费",
    gallery_empty: "尚无保存内容，快去灵境工坊生成吧！",
  }, 
  en: {
    appName: "Fortune Assistant",
    version: "Version v3.8 (Final Payment)",
    traditionalChinese: "Traditional Chinese",
    simplifiedChinese: "Simplified Chinese",
    english: "English",
    userID: "User ID",
    dashboard: "Dashboard",
    fortuneIndex: "Fortune Index",
    familyHarmony: "Family Harmony",
    compatibility: "Compatibility",
    dailyDraw: "Daily Draw",
    tarot: "Tarot",
    nameBlessing: "Name Blessing (12 Coins)",
    rituals: "Rituals",
    yearlyFortune: "Yearly Fortune",
    merits: "Merit Records",
    kindnessShare: "Kindness Share",
    sageChat: "Sage Chat",
    shop: "Lucky Shop",
    lunarCalendar: "Deity Calendar",
    aiStudio: "AI Studio",
    wallet: "My Wallet",
    gallery: "Gallery",
    welcome: "May Mazu bless you with endless luck!",
    totalUsage: "Total Usage (Days)",
    fortuneIndexTitle: "Today's Fortune Index",
    target: "(Target: 90+)",
    dailyTarget: "Daily Merit Goal",
    weeklyFocus: "Weekly Focus",
    fortuneTrend: "Fortune Trend (Simulated)",
    quickGuide: "Quick Guide",
    guideText: "Click the left menu to start your journey.",
    drawFortune: "Draw Fortune",
    drawing: "Drawing...",
    blessing: "Everything Goes Well",
    topBlessing: "Top Blessing",
    topSign: "Great Sign",
    middleSign: "Medium Sign",
    lowSign: "Low Sign",
    heavenMatch: "Perfect Match!",
    goodMatch: "Deep Connection.",
    fateAccept: "Accept the fate.",
    comingSoon: "Coming Soon...",
    fortuneDesc1: "The time has come, wishes will be fulfilled.",
    fortuneDesc2: "Efforts pay off, noble help is present.",
    fortuneDesc3: "Don't rush things; proceed step by step.",
    fortuneDesc4: "Retreat and preserve resources. Wait and see.",
    deepAnalysisTitle: "Deep Analysis & Guidance",
    unlockAnalysis: "Unlock Full Instruction (NT$99)",
    unlockPrompt: "Want to unlock full instruction?",
    paymentProcessing: "Redirecting...",
    paymentSuccess: "Payment Successful!",
    generatingAi: "Master is sensing the heavens...",

    tarot_title: "Tarot Divination",
    tarot_desc: "Focus on your question and pick 3 cards.",
    tarot_start_btn: "Shuffle Deck",
    tarot_picking: "Pick 3 cards intuitively...",
    tarot_reveal_title: "Cards Revealed",
    tarot_past: "Past",
    tarot_present: "Present",
    tarot_future: "Future",
    tarot_unlock_btn: "Unlock Full Reading (NT$99)",
    tarot_locked_msg: "Unlock the divine message hidden in the cards?",

    bless_inputName: "Enter Name",
    bless_selectType: "Select Type",
    bless_type_health: "Health & Safety",
    bless_type_wealth: "Wealth & Abundance",
    bless_type_love: "Love & Harmony",
    bless_type_career: "Career Success",
    bless_generate: "Generate Card (12 Coins)",
    bless_cardTitle: "Blessing Card",
    bless_voice_upgrade: "Add Master's Voice (12 Coins)",
    bless_play_voice: "Play Blessing",

    rituals_title: "Online Rituals",
    rituals_lamp_name: "Peace Lamp (NT$199)",
    rituals_lamp_desc: "Illuminate your path and protect your family.",
    rituals_wealth_name: "Wealth Treasury (NT$888)",
    rituals_wealth_desc: "Fill your wealth treasury and attract abundance.",
    rituals_karmic_name: "Karmic Cleansing (NT$500)",
    rituals_karmic_desc: "Clear karmic debts and purify your soul.",
    rituals_perform_btn: "Register for Ritual",
    rituals_prayer_title: "Ritual Prayer Text",
    rituals_audio_btn: "Listen to Chanting",
    rituals_seasonal_title: "Festival Rituals (Lamp NT$199)",

    peaceLamp: "Peace Lamp",
    lamp_title: "Light a Lamp",
    lamp_desc: "Light a lamp to guide your way.",
    lamp_lit_msg: "The lamp is lit. Blessings are coming.",
    lamp_light_btn: "Light Now (NT$199)",

    yearly_title: "Yearly Fortune Report",
    yearly_desc: "Detailed analysis of your upcoming year.",
    yearly_input_name: "Real Name",
    yearly_input_birth: "Birth Date",
    yearly_unlock_btn: "Unlock Report (NT$299)",
    yearly_report_title: "Detailed Yearly Analysis",

    analysis_title: "Fortune Analysis",
    analysis_inputLesson: "Daily Lesson",
    analysis_inputStability: "Stability Score",
    analysis_calculate: "Calculate Now",
    analysis_trend: "Historical Trend",

    harmony_title: "Harmony Settings",
    harmony_nicknameSubtitle: "Set nicknames.",
    harmony_save: "Save Settings",
    harmony_timeLabel: "Set Time",
    harmony_daysLabel: "Days",
    harmony_setReminder: "Set Reminder",

    comp_title: "Compatibility Check",
    comp_yourLabel: "Your Name",
    comp_partnerLabel: "Partner Name",
    comp_calc: "Calculate",
    comp_result: "Result",

    task_title: "Merit Tasks",
    task_today: "Today's Tasks",
    task_save: "Save Progress",
    task_1: "Help Others",
    task_2: "Wake Up Early",
    task_3: "Meditate",

    share_title: "Share Kindness",
    share_gen_title: "Story Generator",
    share_placeholder: "Describe your good deed...",
    share_btn: "Generate Story",

    chat_title: "Sage Chat",
    chat_select_deity: "Select Deity",
    chat_placeholder: "Enter your question...",
    chat_send: "Send",
    chat_history_clear: "End Chat",
    deity_landgod: "Earth God",
    deity_landgod_desc: "Local guardian (Free)",
    deity_wealth: "God of Wealth",
    deity_wealth_desc: "Business & Investment (10 Coins)",
    deity_matchmaker: "Matchmaker",
    deity_matchmaker_desc: "Love & Marriage (10 Coins)",
    deity_mazu: "Mazu",
    deity_mazu_desc: "Safety & Health (20 Coins)",
    deity_guanyu: "Guan Yu",
    deity_guanyu_desc: "Career & Justice (20 Coins)",
    chat_offering_title: "Make Offering",
    chat_offering_basic: "Incense (10 Coins)",
    chat_offering_premium: "Gold Medal (50 Coins)",
    chat_unlock_btn: "Make Offering & Chat",

    shop_title: "Lucky Shop",
    shop_add: "Add to Cart",
    shop_checkout: "Checkout",
    shop_total: "Total",
    shop_pay: "Pay Now",
    shop_popular: "Popular",
    shop_plan99_name: "Single Unlock (NT$99)",
    shop_plan99_desc: "One-time detailed fortune analysis.",
    shop_plan299_name: "Pro Member (NT$299/mo)",
    shop_plan299_desc: "Daily blessings and weekly insights.",
    shop_item1_name: "Cinnabar Bracelet",
    shop_item1_desc: "Ward off evil (NT$499).",
    shop_item2_name: "Treasure Bowl",
    shop_item2_desc: "Attract wealth (NT$399).",
    shop_item3_name: "Peace Amulet",
    shop_item3_desc: "Carry for safety (NT$299).",
    shop_video_name: "Personalized Video (NT$199)",
    shop_video_desc: "Custom blessing video from Master.",
    shop_wallpaper_name: "Lucky Wallpaper (NT$50)",
    shop_wallpaper_desc: "Daily lucky phone background.",
    shop_micro_title: "Daily Micro-Blessings",
    shop_micro_desc: "Small acts of fortune for your day.",
    shop_delivery_title: "Your Digital Item Delivered",
    shop_delivery_save: "Long press to save",
    shop_input_wish: "Enter your wish",
    shop_input_question: "Enter your question",
    shop_input_zodiac: "Select your Zodiac",

    festival_qingming: "Qingming",
    festival_ghost: "Ghost Festival",
    festival_ghost_14: "July 14th (Lunar)",
    festival_cny: "Lunar New Year",
    festival_lantern: "Lantern Festival",
    festival_mazu: "Mazu Birthday",
    festival_qingming_desc: "Ancestor worship.",
    festival_ghost_desc: "Offerings to spirits.",
    festival_ghost_14_desc: "Prayers for peace.",
    festival_cny_desc: "Welcome the new year.",
    festival_lantern_desc: "Light the wisdom lamp.",
    festival_mazu_desc: "Goddess of the Sea.",

    calendar_title: "Deity Calendar",
    calendar_btn: "Light Lamp (NT$199)",

    ai_studio_title: "AI Spiritual Studio",
    ai_studio_desc: "Generate divine images (Chibi Style) with AI.",
    ai_credits_balance: "Balance",
    ai_buy_credits: "Top Up",
    ai_input_placeholder: "Enter subject (e.g., Mazu, Wealth God)",
    ai_generate_image: "Generate Image",
    ai_generate_video: "Generate Video",
    ai_cost_image: "10 Coins",
    ai_cost_video: "50 Coins",
    ai_generating: "Master is casting spells...",
    ai_pack_1: "Coin Pack - Starter (NT$99)",
    ai_pack_1_desc: "Starter Pack - 1 Video or 10 Images",
    ai_pack_2: "Coin Pack - Value (NT$299)",
    ai_pack_2_desc: "Value Pack - 7 Videos or 35 Images",
    ai_pack_3: "Coin Pack - Pro (NT$999)",
    ai_pack_3_desc: "Pro Pack - 24 Videos or 120 Images",
    ai_badge_hot: "HOT",
    ai_badge_best: "BEST VALUE",
    
    ai_result_title: "✨ Divine Creation ✨",
    ai_error_title: "Connection Interrupted",
    ai_error_desc: "The heavenly signal is weak. Please try again later.",
    ai_refund_msg: "✅ {cost} Coins Refunded",
    ai_bonus_msg: "🎁 +10 Coins Compensation",
    ai_close_btn: "Close & Retry",

    login_title: "Join Fortune Assistant",
    login_subtitle: "Login to accumulate karma & coins",
    login_google: "Sign in with Google (Demo)",
    login_facebook: "Sign in with Facebook (Demo)",
    checkin_title: "Daily Check-in",
    checkin_btn: "Check-in Now",
    checkin_success: "Success!",
    checkin_streak: "Streak",
    checkin_reward: "+10 Coins",

    wallet_title: "My Wallet",
    gallery_title: "My Gallery",
    support_btn: "Contact Support",
    wallet_history: "Transactions",
    wallet_topup: "Top Up",
    wallet_spend: "Spend",
    gallery_empty: "No saved items yet. Visit AI Studio!",
  }
};
